language: php
php:
- 5.6
- 7.0

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - composer exec config-standard
  - php console generate:app Payroll

script: phpunit
